# Generated by Django 3.0.8 on 2021-09-04 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='download',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='movies',
            name='rating',
            field=models.CharField(default='', max_length=10),
        ),
    ]
